# Jekyll Configuration
theme: jekyll-theme-minimal

# Basic Information
title: Sam Moore
description: Duke Robotics Ph.D.
logo: assets/img/avatar.png

# Contact & Social Links
url_github: https://github.com/samavmoore
url_email: sam.a.moore@duke.edu
url_linkedin: https://www.linkedin.com/in/sam-moore-a060b0199
# url_steam: https://steamcommunity.com/id/silvery107
url_scholar: https://scholar.google.com/citations?hl=en&user=ZwNU_H0AAAAJ
# url_cv: docs/CV_Yulun_Zhuang.pdf

# Optional Settings
# chinese_name: assets/img/name_kaiti.svg
google_analytics: G-YK2GLKKT0V
